from . import test_schema_smoke  # noqa: F401
from . import test_training_models  # noqa: F401
from . import test_attendance  # noqa: F401
from . import test_security  # noqa: F401
from . import test_survey_survey  # noqa: F401
from . import test_survey_training_day  # noqa: F401
from . import test_survey_user_input  # noqa: F401
from . import test_training_analytics  # noqa: F401
from . import test_training_day_workflow  # noqa: F401
from . import test_operational_api_auth  # noqa: F401
from . import test_operational_api_dashboards  # noqa: F401
from . import test_operational_api_trainee  # noqa: F401
from . import test_operational_api_supervisor  # noqa: F401
from . import test_operational_api_trainer  # noqa: F401
from . import test_operational_api_security  # noqa: F401
from . import test_operational_api_health  # noqa: F401
from . import test_training_report  # noqa: F401
from . import test_training_notification  # noqa: F401
from . import test_training_audit_log  # noqa: F401
from . import test_e2e_full_scenario  # noqa: F401
